version: "1"

services:
  web1:
    restart: "always"
    build: ./web
    ports:
      - "8081:80"
    networks:
      - network1
  web2:
    restart: "always"
    build: ./web
    ports:
      - "8082:80"
    networks:
      - network1
  lb:
    restart: "always"
    build: ./lb
    depends_on:
      - web1
      - web2
    ports:
      - 8080:80
    networks:
      - network1

networks:
  network1:
    name: network1
    ipam:
      config:
        - subnet: 172.50.0.0/24